Collection of grammar and syntax changes
aseprite/docs pull request #13
Opened 2022-07-01 15:59 UTC by brickviking

I thought I'd start easy and tweak various phrases to sound better. I speak English natively and have done odd little tidy-up jobs for other projects as well.

2022-07-01 21:42 UTC, brickviking commented
My apologies, I completely forgot to put these changes into a separate branch. I'll do better next PR.

2022-07-05 17:40 UTC, martincapello commented on basics.md
We would like to keep this line informal as is. However, you are right about replacing "basics" with "basic".

2022-07-05 17:45 UTC, martincapello commented on basics.md
> +an array of editable graphic elements [cels](cel.md) with images/pixels that
Could you elaborate a bit why adding the _elements_ word would make this line clearer? Generally we prefer using fewer words if the meaning doesn't change.

2022-07-05 17:48 UTC, martincapello commented on basics.md
> +subsequent layer is added over top of it. Layers assist you by dividing
👍

2022-07-05 17:48 UTC, martincapello commented on basics.md
> +affecting the contents of other cels, which make them ideal for
💯

2022-07-05 17:49 UTC, martincapello commented on basics.md
> + You may choose from any of several other file formats during _Save As_ and _Export _as well, depending on your color depth choices and personal preferences!)
👍

2022-07-05 17:59 UTC, martincapello commented on basics.md
As said previously, we want to keep the informal style. However, I do feel that we should change this a bit. Do you think that something like the following would work?:
```
Check-out the [workspace](workspace.md) section to know more about the elements
in the window, and the [workflow](workflow.md) section for more details.
```
Or
```
Look at the [workspace](workspace.md) section to know more about the elements
in the window, and the [workflow](workflow.md) section for more details.
```

2022-07-05 18:00 UTC, martincapello commented on basics.md
> +can use them from the very beginning to make better use of Aseprite:
💯

2022-07-05 18:00 UTC, martincapello commented on basics.md
> +* <kbd>Alt+click</kbd> allows you to pick colors from the active image
💯

2022-07-05 18:01 UTC, martincapello commented on basics.md
> +  pan your view of the sprite you are currently editing. This is useful when
👍

2022-07-05 18:02 UTC, martincapello commented on canvas.md
> +You can remove transparent borders automatically from the canvas
💯

2022-07-05 18:18 UTC, martincapello commented on cel.md
> +the Timeline.
The _x_ and _y_ position of the image is the position of it in the canvas. So, _canvas_ is right in this case.

2022-07-05 18:19 UTC, martincapello commented on layers.md
> +One sprite can be subdivided into several layers. You can see them
👍

2022-07-05 18:20 UTC, martincapello commented on layers.md
> +name by double-clicking the layer, or from the *Layer > Properties* menu (<kbd>Shift+P</kbd> key).
👍

2022-07-05 18:20 UTC, martincapello commented on layers.md
> +You can have several of these in the same sprite.
💯

2022-07-05 18:20 UTC, martincapello commented on layers.md
> +one unit.
💯

2022-07-05 18:29 UTC, martincapello commented on menu-bar.md
> +You can show the Aseprite menu bar by checking the [*Edit >
We want to keep the _anyway_. Because we want to say informally that you can still make the menu bar visible on macOS in spite of being hidden by default.

2022-07-05 18:30 UTC, martincapello commented on overview.md
> +beginning. If you have some questions you can start looking at the
👍

2022-07-05 18:32 UTC, martincapello commented on overview.md
> +  * [Create a new Sprite](new-sprite.md) or [Open a saved Sprite](open.md)
I think both can work. I'll let @dacap to decide here.

2022-07-05 18:32 UTC, martincapello commented on sprite.md
> +1. It has a [color mode](color-mode.md), which tells you how many
👍

2022-07-05 18:35 UTC, martincapello commented on sprite.md
> +1. A [color profile](color-profile.md) which says what color space the sprite's RGB values will use.
Not sure about this. @dacap

2022-07-05 18:35 UTC, martincapello commented on sprite.md
> +   that there are two kinds of layers:
👍

2022-07-05 18:36 UTC, martincapello commented on sprite.md
> +1. Each layer/frame intersection is called a [cel](cel.md),
👍

2022-07-05 18:37 UTC, martincapello commented on sprite.md
> +sprite as a grid. Rows are layers and columns are frames, each
💯

2022-07-05 18:48 UTC, martincapello commented on workspace.md
> +*View > Timeline* menu option or <kbd>Tab</kbd> key. (It also pops up
The proposed version sounds good to me, what do you think @dacap ?

2022-07-05 18:48 UTC, martincapello commented on workspace.md
> +You should become familiar with these window elements:
👍

2022-07-05 18:54 UTC, martincapello commented on workspace.md
> +information about the current sprite.
I like the reference to the status bar you proposed here. I would just replace _status bar_ by `[status bar](status-bar.md)` to be consistent with the other elements mentioned.

2022-07-05 18:58 UTC, martincapello commented on workspace.md
> +with the <kbd>Left Mouse Button</kbd>:
Sounds good to me. What do you think @dacap ?

2022-07-05 22:27 UTC, brickviking commented on basics.md
> +an array of editable graphic elements [cels](cel.md) with images/pixels that
Looks like I missed that - that's what comes of not using an editor with a markdown preview. I'll revert that change, as "cels" is what you mean by elements. I could propose "... graphic elements called [cels](cel.md) with ...".

2022-07-05 22:43 UTC, brickviking commented on basics.md
We could also try this:
```
Check the [workspace](workspace.md) section to learn more about window elements, and the [workflow](workflow.md)
for more details.
```

2022-07-05 23:00 UTC, brickviking commented on basics.md
Okay, how about this then:
```
This page talks about the basic principles of Aseprite.
```
or
```
This page talks about Aseprite's basic principles.
```
I like the second, as it more closely meets the informality brief.

2022-07-05 23:17 UTC, brickviking commented on overview.md
> +  * [Create a new Sprite](new-sprite.md) or [Open a saved Sprite](open.md)
My main contention is the term "existent". We don't generally use it in that way. I've seen simply `Open File...`, as everyone "generally" considers that you can't open one that doesn't already exist.

2022-07-05 23:55 UTC, brickviking commented on workspace.md
> +information about the current sprite.
Sounds good. Done.

2022-07-06 00:10 UTC, brickviking commented on cel.md
> +the Timeline.
Done. Reverted.

2022-07-06 13:01 UTC, martincapello commented on basics.md
If it were up to me, I would just remove the whole line, since IMO it doesn't say more than the document's title. But, yesterday, when I talked with David a bit, he actually liked the "Here you can..." instead of saying "This page...". It made sense to me, because we can assume that the user knows that he is in a page, so there is no need to say it. So I would just fix the original line by fixing the _basics_ word. 
Anyway, @dacap will have to decide.

2022-07-06 13:03 UTC, martincapello commented on basics.md
> +an array of editable graphic elements [cels](cel.md) with images/pixels that
Oh I see! Let's keep the original then. Thanks!

2022-07-06 13:05 UTC, dacap commented on basics.md
Hi there, we're keeping "Here you can learn the basic principles behind Aseprite." It's a minor phrase and we prefer to keep the style as it is.

2022-07-06 13:09 UTC, dacap commented on overview.md
> +  * [Create a new Sprite](new-sprite.md) or [Open a saved Sprite](open.md)
It should say "Open an existing one". I'd prefer to avoid using "Open" and "saved" in the same phrase in this item.
```suggestion
  * [Create a new Sprite](new-sprite.md) or [Open an existing one](open.md)
```

2022-07-06 13:12 UTC, dacap commented on sprite.md
> +1. A [color profile](color-profile.md) which says what color space the sprite's RGB values will use.
We can say:
```suggestion
1. A [color profile](color-profile.md) which indicates what color space the RGB values are in.
```

2022-07-06 13:13 UTC, dacap commented on workspace.md
> +*View > Timeline* menu option or <kbd>Tab</kbd> key. (It also pops up
The new rewording is fine 👍

2022-07-06 13:17 UTC, dacap commented on workspace.md
> +with the <kbd>Left Mouse Button</kbd>:
👍

2022-07-07 09:09 UTC, brickviking commented on basics.md
Okay, I'll change it back. That should be the last of my changes in this pull request. As I said, the rest of the changes will be applied in separate branches.

2022-07-07 09:11 UTC, brickviking commented
That should be all the relevant changes from me, so you're free to go ahead.

2022-07-07 14:41 UTC, martincapello reviewed
Looks good, just a few more details to wrap this up

2022-07-07 14:41 UTC, martincapello commented on overview.md
> +  * [Create a new Sprite](new-sprite.md) or [Open a saved Sprite](open.md)
@brickviking would you mind to make the suggested fix?

2022-07-07 14:41 UTC, martincapello commented on menu-bar.md
> +You can show the Aseprite menu bar by checking the [*Edit >
```suggestion
Anyway you can show the Aseprite menu bar by checking the [*Edit >
```

2022-07-07 14:41 UTC, martincapello commented on basics.md
I like the proposed rewording for this. @dacap what do you think?

2022-07-07 23:43 UTC, brickviking commented on basics.md
I would amend that very slightly (adding the word section):
```
Check the [workspace](workspace.md) section to learn more about window elements,
and the [workflow](workflow.md) section for more details.
```

2022-07-07 23:46 UTC, brickviking commented on menu-bar.md
> +You can show the Aseprite menu bar by checking the [*Edit >
Hm. That "Anyway" with no comma is not how we'd write it, even informally. How about using "However," instead, like this:
```
However, you can show the Aseprite menu bar by checking the [*Edit >
```
or alternatively:
```
Anyway, you can show the Aseprite menu bar by checking the [*Edit >
```

Sorry it took me a little time to catch up on this.

2022-07-08 11:27 UTC, brickviking commented on overview.md
> +  * [Create a new Sprite](new-sprite.md) or [Open a saved Sprite](open.md)
Okay, now I'm officially confused. Anyhow, change pushed back to "Open an existing one" for now.

2022-07-10 13:10 UTC, brickviking commented
Just touching base with these commits - are we good to go, or do I need to check/change something?

2022-07-10 13:21 UTC, dacap commented on basics.md
I prefer the original one as it's shorter and to the point. As it's a change of style, I'd keep the original one and keep only typo fixes.

2022-07-10 13:22 UTC, dacap commented
As a general rule: Prefer to keep the documentation as short as possible, and don't change style if it's not needed.

2022-07-10 13:24 UTC, dacap commented
As a final note, about the changes in the Workflow section in Basics, as we are already in a Workflow section:

<img width="877" alt="Screen Shot 2022-07-10 at 10 23 22" src="https://user-images.githubusercontent.com/39654/178146774-a37b6f4c-8f19-475b-8baf-16017711825d.png">

That's why it says at the end "See workflow section for more details." Because we're already describing the workflow. Please check the changes in the context.

2022-07-20 12:12 UTC, martincapello requested changes
Just one last change

2022-07-20 12:12 UTC, martincapello commented on basics.md
@brickviking we will keep the original text, could you revert this change please?

2022-07-20 12:32 UTC, dacap commented on basics.md
@martincapello you can squash all commits and revert/amend the necessary changes.

2022-07-20 12:37 UTC, brickviking commented on basics.md
That's weird, my text from brickviking:main:basics.md reads what you wanted it to read.
```
See the [workspace](workspace.md) to learn more about the elements of the Aseprite window, and the [workflow](workflow.md) section for more details.
```
Am I still missing something?

2022-07-20 13:13 UTC, martincapello approved these changes
🥇

2022-07-20 13:18 UTC, merged