Some wording changes
aseprite/docs pull request #19
Opened 2022-07-22 16:10 UTC by brickviking

Unsure about 'Color profiles indicate...' paragraph

2022-07-26 13:35 UTC, martincapello requested changes
Looking good. Left a few comments

2022-07-26 13:35 UTC, martincapello commented on color-profile.md
> +But what does a position in this 3D cube mean? We know that
💯

2022-07-26 13:35 UTC, martincapello commented on color-profile.md
> +is white, etc. But what is [white](https://en.wikipedia.org/wiki/White_point) exactly?
💯

2022-07-26 13:35 UTC, martincapello commented on color-profile.md
> +scanner, etc.)  must be calibrated to convert the light in the ambient environment
Not sure about this. Was the use of ambient and environment intentional or did you want to replace ambient by environment?

2022-07-26 13:35 UTC, martincapello commented on color-profile.md
> +these RGB values are. What does it mean to be pure red,
💯

2022-07-26 13:35 UTC, martincapello commented on color-profile.md
> +Images on the Internet generally use the
💯

2022-07-26 13:35 UTC, martincapello commented on color-profile.md
> +Since v1.2.10-beta2, Aseprite can
Is this actually wrong? I thought it could be said both ways

2022-07-28 01:14 UTC, brickviking commented on color-profile.md
> +scanner, etc.)  must be calibrated to convert the light in the ambient environment
InEnglish, I haven't seen "ambient" used on its own. Because it's an adjective, it's used in relation to another word, such as ambient temperature, ambient environment (as in the environment that surrounds the item). In this case it could become simply "environment" if you wished. I just think this states the original better.

2022-07-28 01:25 UTC, brickviking commented on color-profile.md
> +Since v1.2.10-beta2, Aseprite can
Yes, it's wrong. Another example would be:  "Since Monday, news will be at 5 pm instead". Instead of "Since news, Monday will be at 5pm instead". The version is a fixed point in time, hence the word "Since <some-version>, the program does this instead".

2022-07-28 01:34 UTC, dacap commented on color-profile.md
> +Since v1.2.10-beta2, Aseprite can
It could say something like “Since Aseprite v1.2.10-beta2, you can…” or “it can”. Even more, in some places **Aseprite vX** is in bold, just to highlight the version of Aseprite (or we can just use the version without “Aseprite”).

2022-07-28 01:48 UTC, brickviking commented on color-profile.md
> +Since v1.2.10-beta2, Aseprite can
Sounds good to me, I'll make a modification on my end.

2022-07-28 17:03 UTC, martincapello approved these changes
LGTM!

2022-07-28 17:03 UTC, martincapello commented on color-profile.md
> +scanner, etc.)  must be calibrated to convert the light in the ambient environment
I see, that makes sense, thank you for the clarification!

2022-07-28 17:03 UTC, martincapello commented on color-profile.md
> +[color profiles in `.aseprite` files](https://github.com/aseprite/aseprite/blob/master/docs/ase-file-specs.md#color-profile-chunk-0x2007) too.
💯

2022-07-28 17:04 UTC, merged