Transformations Update
aseprite/docs pull request #24
Opened 2022-07-25 10:14 UTC by thkwznk

2022-07-25 18:17 UTC, martincapello requested changes
Looking great! I just made a minor suggestion and requested to transform the commented line into an issue.

2022-07-25 18:17 UTC, martincapello commented on rotate.md
> +<!-- FUTURE: Expand tools section with selection tools and link them here -->
Could you please delete this line? I know that this line is not rendered by Github's markdown parser, but the one we use (a modified version of php's Parsedown parser) does, so when I look at this from aseprite's website it shows me the whole comment, start and end markers included. 
However I would like to keep the task you describe, so it would be great if you can create an issue to keep track of this.

2022-07-25 18:17 UTC, martincapello commented on rotate.md
> +While RotSprite is widely accepted as an algorithm producing better results, the choice depends only on users' preferences.
I think I would replace 
"the choice depends only on users' preferences."
by
"the choice is up to you." or "the choice is up to your preferences."

2022-07-26 17:54 UTC, thkwznk commented on rotate.md
> +<!-- FUTURE: Expand tools section with selection tools and link them here -->
Done 👍

2022-07-26 17:56 UTC, thkwznk commented on rotate.md
> +While RotSprite is widely accepted as an algorithm producing better results, the choice depends only on users' preferences.
Changed to "the choice is up to your preferences."

2022-07-26 18:05 UTC, martincapello approved these changes
Looks good to me! 🥇

2022-07-26 18:08 UTC, merged