Transformations Section Update
aseprite/docs pull request #26
Opened 2022-08-07 19:03 UTC by thkwznk

2022-08-10 14:47 UTC, dacap commented
Hi @thkwznk, a PR should avoid to merge other branches (you can rebase your branch and force push in your own branch). Anyway I'll remove the write access just in case (it's too risky for rebase/force pushes). So you can fork the docs repository in your own user and send PRs from there.

P.S. I've just published the rotate page: http://aseprite.localhost/docs/rotate/

2022-08-10 18:27 UTC, thkwznk commented
@dacap Sure, I'll fork the repository, cherry-pick the changes to a new branch and continue from there. Any feedback on the content itself?

2022-08-10 20:39 UTC, dacap commented
Thanks @thkwznk, I'll review it right now, some general recommendations would be to avoid changing the style of italic text (we use `*this*` instead of `_this_`). Now I'll make other comments inline.

2022-08-10 20:59 UTC, dacap requested changes
So far so good @thkwznk 🙏 some minor changes. It's nice to see these sections evolving. Are the most abandoned parts of the documentation.

2022-08-10 20:59 UTC, dacap commented on canvas.md
> +<!-- PREVIEW: GIF, change canvas size to a bigger one, with previously placed sprite that is only partially visible in the original, small canvas and being shown in full after the change -->
Our current Markdown parser (and old version of Parsedown.php) doesn't support HTML comments, but I'll try to add support to ignore these comments when we parse, they are useful to mark missing parts of the docs 👍

2022-08-10 20:59 UTC, dacap commented on rotate-canvas.md
> +You can rotate the [canvas](canvas.md) using _Sprite > Rotate Canvas_ menu. The available options are:
Maybe a minor change:
```suggestion
You can rotate the [whole canvas](canvas.md) using *Sprite > Rotate Canvas* menu. The available options are:
```

2022-08-10 20:59 UTC, dacap commented on transformations.md
> +Sprite or a selection can be transformed using options mostly found under the _Edit_ menu, or by using selection handles:
```suggestion
A sprite or a selection can be transformed using options mostly found under the *Edit* menu, or by using the selection handles:
```

2022-08-10 20:59 UTC, dacap commented on transformations.md
> +- [Flip canvas](flip-canvas.md)
Prefer using `*` for bulleted lists.
```suggestion
* [Flip canvas](flip-canvas.md)
```
etc.

2022-08-10 20:59 UTC, dacap commented on transformations.md
> +
```suggestion
Transformations will be applied to every layer, frame, and cel selected on the [timeline](timeline.md). If there's no selection on the timeline, transformations will be applied only to the active cel.

```

2022-08-10 22:14 UTC, thkwznk commented on canvas.md
> +<!-- PREVIEW: GIF, change canvas size to a bigger one, with previously placed sprite that is only partially visible in the original, small canvas and being shown in full after the change -->
I remember @martincapello mentioning this in my last PR. I leave these only as markers in the draft for the parts that I need to fill in later - I'll either replace them with images or turn them into separate issues before submitting a final PR.

2022-08-10 22:17 UTC, thkwznk commented
> ...some general recommendations would be to avoid changing the style of italic text (we use \*this\* instead of \_this\_).

I use automatic formatting a lot, so I'll set it up to use the \* for italics and bullet lists. 👍

2022-08-12 13:13 UTC, thkwznk commented on rotate-canvas.md
> +You can rotate the [canvas](canvas.md) using _Sprite > Rotate Canvas_ menu. The available options are:
Fixed on the fork in [this commit](https://github.com/thkwznk/aseprite-docs/commit/360a6a13688dd9ad92d844728293c8aad9df7a48).

2022-08-12 13:13 UTC, thkwznk commented on transformations.md
> +- [Flip canvas](flip-canvas.md)
Fixed on the fork in [this commit](https://github.com/thkwznk/aseprite-docs/commit/360a6a13688dd9ad92d844728293c8aad9df7a48).

2022-08-12 13:13 UTC, thkwznk commented on transformations.md
> +Sprite or a selection can be transformed using options mostly found under the _Edit_ menu, or by using selection handles:
Fixed on the fork in [this commit](https://github.com/thkwznk/aseprite-docs/commit/360a6a13688dd9ad92d844728293c8aad9df7a48).

2022-08-12 13:13 UTC, thkwznk commented on transformations.md
> +
Fixed on the fork in [this commit](https://github.com/thkwznk/aseprite-docs/commit/360a6a13688dd9ad92d844728293c8aad9df7a48).

2022-08-12 15:24 UTC, thkwznk commented
I'm closing this one and will reopen a final one with visuals from the forked repository.

2022-08-12 15:24 UTC, closed without merging